### PR TITLE
Multi-requirement containers web app

### PR DESCRIPTION
**Pull request by anatskiy**
screenshot

This adds an app, which generates a TSV file with selected packages. The file has a name of a mulled container v2: `mulled-v2-<hash_of_packages>:<hash_of_versions>`

If it's possible, there are plans to automatically create a PR with a mulled container.

[Demo](http://anatskiy.github.io/multireqcontainers/).

### CODE REVIEW

**Comment by bgruening** [comment]
Demo link is here: http://anatskiy.me/multireqcontainers/

**Comment by jmchilton** [comment]
This is stunningly beautiful.

**Comment by jmchilton** [comment]
Thanks a ton @anatskiy !

**Comment by jmchilton** [comment]
Should we update the GUI to say "Multi-package Containers". requirement is a very Galaxy-centric word and it would probably be better to use a Conda centric word. I think we should rename the repository also - I just through this together for testing and now it feels so official with that gorgeous GUI 😆. Maybe `multi-package-registry` or `multi-package-containers`?

**Comment by bgruening** [comment]
:+1: for "multi-package-containers"

**Comment by bgruening** [comment]
@jmchilton you should have the privileges to move it over to biocontainers, if not let me know.

**Comment by bgruening** [comment]
Here is the URL: https://jmchilton.github.io/multireqcontainers

**Pull request merged**
